config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#top'
  get 'home/about' => "home#about"
  get 'relationships/follower' => 'relationships#follower'
  get 'relationships/follow' => 'relationships#follow'


  resources :users do
  	member do
      get :followings
      get :followers
    end
  end

  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
	has_many :favorites, dependent: :destroy
	has_many :book_comments, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :user
    belongs_to :book
    validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :user
	belongs_to :follow, class_name: 'User'

	validates :user_id,presence: true
	validates :follow_id,presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  attachment :profile_image

  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name:'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

 def follow(other_user)
    unless self == other_user
      self.relationships.create(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, length: {maximum: 20, minimum: 2}
  validates :introduction, length: {maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	before_action :configure_permitted_parameters, if: :devise_controller?


  protected
  def configure_permitted_parameters
  added_attrs = [:name, :email, :password, :password_confirmation ]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
    end

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

   def counts(user)
    @count_microposts = user.microposts.count
    @count_followings = user.followings.count
    @count_followers = user.followers.count
  end





end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
	def create
		book = Book.find(params[:book_id])
		# comment = Book.new(book_params)
		# comment.user.id = current_user.id
		comment = current_user.book_comments.new(book_comment_params)
		comment.book_id = book.id
		comment.save
		redirect_to book_path(book)
	end

	def destroy
		BookComment.find_by(id: params[:id],book_id: params[:book_id]).destroy
		redirect_to book_path(params[:book_id])
	end

	private
	def book_comment_params
		params.require(:book_comment).permit(:comment)
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def show
    @book = Book.find(params[:id])
    @newbook = Book.new
    @book_comment = BookComment.new
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: "You have created book successfully."
    else
      @books = Book.all
      render action: :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    
    if @book.user.id != current_user.id
      redirect_to books_path
  end
  end


  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render action: :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path, notice: 'Book was successfully destroyed.'
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	def create
		book = Book.find(params[:book_id])
		favorite = current_user.favorites.new(book_id: book.id)
        favorite.save
        redirect_to request.referrer || root_url
	end

	def destroy
		book = Book.find(params[:book_id])
        favorite = current_user.favorites.find_by(book_id: book.id)
        favorite.destroy
        redirect_to request.referrer || root_url
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController


	def create
		user = User.find(params[:follow_id])
		following = current_user.follow(user)
	    redirect_to user
	end

	def destroy
		user = User.find(params[:follow_id])
		following = current_user.unfollow(user)
		redirect_to user
    end


    def follow
    	user = User.find(params[:user_id])
    	@users = user.followings
    end

    def follower
    	user = User.find(params[:user_id])
    	@users = user.followers
    end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render action: :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_newform.html.erb
<%= form_for(book) do |f| %>
	<div class="field row">

<% if book.errors.any? %>
   <h3><%= book.errors.count %>errors prohibited this book from being saved:</h3>
     <ul>
    <% book.errors.full_messages.each do |message|%>
     <li><%= message %></li>
   <% end %>
  </ul>
 <% end %>
		<%= f.label :Title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
     	</div>

 	<div class="field row">
 		<%= f.label :Opinion %>
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
     	</div>

 	<div class="actions row">
 		<%= f.submit "Create Book",class: "btn btn-primary col-xs-12" %>
 	</div>
 <% end %>

app/views/books/edit.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">

		<h1>Editing Book</h1>

		<%= form_for(@book) do |f| %>
		<div class="field row">

        <% if @book.errors.any? %>
        <h3><%=@book.errors.count %>errors prohibited this book from being saved:</h3>
        <ul>
        <% @book.errors.full_messages.each do |message|%>
        <li><%= message %></li>
        <% end %>
        </ul>
        <% end %>
		<%= f.label :Title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
     	</div>

 	<div class="field row">
 		<%= f.label :Opinion %>
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
     	</div>

 	<div class="actions row">
 		<%= f.submit "Update Book",class: "btn btn-primary col-xs-12" %>
 	</div>
 <% end %>
		<%= link_to "Show", book_path(@book), class: "book_#{@book.id}" %>
		<%= link_to "Back", books_path, class: "back" %>

	</div>
	<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Books index</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
					<%=link_to attachment_image_tag(book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg",size: "60x60"), book.user %>

					</td>
					<td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>


					<% if book.favorited_by?(current_user) %>
					<td><%= link_to book_favorites_path(book), method: :delete do %>
                     <i class="fa fa-heart like-btn" aria-hidden="true" style="color: red;"></i>
                      <%= book.favorites.count %>
                      <% end %>
                     </td>
              <% else %>
                       <td>
                       <%= link_to book_favorites_path(book), method: :post do %>
                       <i class="fa fa-heart-o" aria-hidden="true"></i>
                       <%= book.favorites.count %>
                      <% end %>
                       </td>


                  <% end %>
                  <td><%= link_to "#{book.book_comments.count} コメント",book_path(book.id) %></td>
				</tr>
				<% end %>
			</tbody>
		</table>

		<!--books一覧 -->


	</div>
</div>

app/views/books/show.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile',user: @book.user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @newbook %>

	</div>

	<div class="col-xs-9">
		<h2>Book detail</h2>

		<table class="table">
				<tr>
					<td>
						<%= link_to user_path(@book.user) do %>
							<%= attachment_image_tag(@book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg") %><br>
						<%= @book.user.name %>
						<% end %>
					</td>
					<td><%= link_to @book.title, book_path(@book) %></td>
					<td><%= @book.body %></td>
					<% if @book.user.id == current_user.id %>
					<td><%= link_to "Edit", edit_book_path(@book)%></td>
					<td><%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
					<%end%>


					<% if @book.favorited_by?(current_user) %>
					<td><%= link_to book_favorites_path(@book), method: :delete do %>
                     <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
                      <%= @book.favorites.count %>
                      <% end %>
                     </td>
                     <% else %>
                       <td>
                       <%= link_to book_favorites_path(@book), method: :post do %>
                       <i class="fa fa-heart-o" aria-hidden="true"></i>
                       <%= @book.favorites.count %>
                      <% end %>


                       </td>
                       <% end %>

                       <td><i class="fa fa-comment"></i>
                       	<%= @book.book_comments.count %>
                       	<% @book.book_comments.count %>件コメント
                       </td>
                   </tr>
                   </table>

                   <table>



                       <% @book.book_comments.each do |book_comment| %>
                       <tr>
                         <td><%= attachment_image_tag(book_comment.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg",size: "40x40") %></td>

                       	<td><%= book_comment.comment %></td>
                       	<% if book_comment.user == current_user%>
                        <td>
                         <%= link_to "削除", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-danger pull-right" %>
                         </td>
                         <% end %>
                         <tr><td>
                         	<%= book_comment.user.name %></td>

                       	<% end %>

			     </table>
			     <%= form_for [@book, @book_comment] do |f| %>
                        <div class="row">
                        <div class="col-sm-12">
                       <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
                         </div>
                         </div>
                        <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
                        <% end %>

	</div>
</div>

app/views/home/about.html.erb
<h1>welcome to<span class="glyphicon glyphicon-book"></span>
<strong>Bookers</strong>  !!</h1>

app/views/home/top.html.erb
<div class="row">
	<div class="main col-md-offset-3 col-md-6">
		<h1>welcome to<span class="glyphicon glyphicon-book"></span>
			<strong>Bookers</strong>  !!</h1>
			<p>In <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>,</p>
			<p>you can share and exchange your opinions , inpressions , and emotions</p>
			<p>about varioius books!</p>

			<div class="btn-wrapper">
				<div class="row">
					<p><%=link_to "Log in", user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %></p>
				</div>
				<div class="row">
					<p><%=link_to "Sign Up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %></p>
				</div>
			</div>

	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">

        <nav class="nav navbar-nav navbar-left">
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>

              <li><%= link_to ' Home', user_path(current_user.id), class: 'glyphicon glyphicon-home home' %></li>
              <li><%= link_to ' Users', users_path, class: 'glyphicon glyphicon-user users' %></li>
              <li><%= link_to ' Books', books_path, class: 'glyphicon glyphicon-book books' %></li>
              <li><%= link_to ' logout', destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %></li>
            <% else %>
              <li><%= link_to ' Home', root_path, class: 'glyphicon glyphicon-home home' %></li>
              <li><%= link_to ' About', home_about_path, class: 'glyphicon glyphicon-link about' %></li>
              <li><%= link_to ' Sign up', new_user_registration_path, class: 'glyphicon glyphicon-edit sign_up' %></li>
              <li><%= link_to ' login', user_session_path, class: 'glyphicon glyphicon-log-in sign_in' %></li>
            <% end %>
          </ul>
        </nav>

      </div>
    </header>

    <div class="container">
      <p id="notice"><%= notice %></p>



<%= yield %>
    </div>

    <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/relationships/follow.html.erb
<div class="col-xs-11">

<h2>Follow Users</h2>
<!--users一覧 -->
<table class="table">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @users.each do |user| %>
		<tr>
			<td><%= attachment_image_tag(user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg",size: "60x60") %></td>
			<td><%= user.name %></td>

			<td>フォロー数:<%= user.followings.count %></td>
			<td>フォロワー数:<%= user.followers.count %></td>

			<td><%= link_to "Show", user_path(user.id)%></td>
		</tr>
		<% end %>
	</tbody>
</table>

</div>
</div>
<!--users一覧 -->

app/views/relationships/follower.html.erb
<div class="col-xs-11">

<h2>Follower Users</h2>
<!--users一覧 -->
<table class="table">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @users.each do |user| %>
		<tr>
			<td><%= attachment_image_tag(user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg",size: "60x60") %></td>
			<td><%= user.name %></td>

			<td>フォロー数:<%= user.followings.count %></td>
			<td>フォロワー数:<%= user.followers.count %></td>

			<td><%= link_to "Show", user_path(user.id)%></td>
		</tr>
		<% end %>
	</tbody>
</table>

</div>
</div>

app/views/users/_profile.html.erb
<table class="table">
	<tr><%= attachment_image_tag(user,:profile_image,:fill,100,100,fallback: "no_image.jpg") %></tr>

     <tbody><tr></tr>
	<tr>
		<th>name</th>
		<th><%= user.name %></th>
	</tr>

	<tr>
		<th>introduction</th>
		<th><%= user.introduction %></th>
	<tr>
		<th>follows</th>
		<th><%= link_to relationships_follow_path(user_id: user.id) do  %><%= user.followings.count %><% end %></th>
	<tr>
		<th>followers</th>
        <th><%= link_to relationships_follower_path(user_id: user.id) do %><%= user.followers.count %><% end %></th>
		<% unless current_user == user %>
		<% if current_user.following?(user) %>
		<br>

        <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
     <tr>
     	<th><%= hidden_field_tag :follow_id, user.id %></th>
        <th><%= f.submit 'フォローを外す', class: 'btn btn-danger btn-block' %></th>
    </tr>
        <% end %>
        <% else %>
    <tr>
        <%= form_for(current_user.relationships.build) do |f| %>
         <th><%= hidden_field_tag :follow_id, user.id %></th>
         <th><%= f.submit 'フォローする', class: 'btn btn-primary btn-block' %></th>
    </tr>



       <% end %>
       <% end %>
      <% end %>
	</tr></tbody>
</table>

<div class="row">
	<%= link_to '', edit_user_path(current_user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
</div>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_for(@user) do |f| %>

	<!-- エラーメッセージ表示-->
	<% if @user.errors.any? %>
		<div id="error_explanation">
			<h3><%= @user.errors.count %>error prohibited this obj from being saved:</h3><
			<ul>
				<% @user.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<!-- エラーメッセージ表示-->

	<div class="field">
		<%= f.label :title %>
		<%= f.text_field :name, class: "name" %>
	</div>

	<div class="field">
		<%= f.label :image %>
		<%= f.attachment_field :profile_image, class: "user_image" %>
	</div>

	<div class="field">
		<%= f.label :introduction %>
		<%= f.text_area :introduction, class: "introduction" %>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>

<% end %>

app/views/users/index.html.erb
<div class="row">
	<div class="col-xs-3">
<h2>User info</h2>
<%= render 'users/profile', user: current_user %>

<h2>New book</h2>
<%= render 'books/newform', book: @book %>
</div>
<div class="col-xs-9">

<h2>Users</h2>
<!--users一覧 -->
<table class="table">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @users.each do |user| %>
		<tr>
			<td><%= attachment_image_tag(user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg",size: "60x60") %></td>
			<td><%= user.name %></td>

			<td>フォロー数:<%= user.followings.count %></td>
			<td>フォロワー数:<%= user.followers.count %></td>
			<% unless current_user == user %>
              <% if current_user.following?(user) %>
               <td><%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
               <%= hidden_field_tag :follow_id, user.id %>
               <%= f.submit 'Unfollow', class: 'btn btn-danger btn-block' %>
               </td>
              <% end %>
              <% else %>
               <td>
               <%= form_for(current_user.relationships.build) do |f| %>
               <%= hidden_field_tag :follow_id, user.id %>
               <%= f.submit 'Follow', class: 'btn btn-primary btn-block' %>
               </td>
               <% end %>
              <% end %>
            <% end %>

			<td><%= link_to "Show", user_path(user.id)%></td>
		</tr>
		<% end %>
	</tbody>
</table>

</div>
</div>
<!--users一覧 -->

app/views/users/show.html.erb
<div class="row">
	<div class="col-xs-3">
		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>
	</div>

	<div class="col-xs-9">
		<h2>Books</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to user_path(book.user) do %>
							<%= attachment_image_tag @user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg",size: "40x40" %>
						<% end %>
					</td>
					<td><%= link_to book.title,book_path(book)%></td>
					<td><%= book.body %></td>
					<td><%= link_to "#{book.book_comments.count} コメント",book_path(book.id) %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<!--books一覧 -->
	</div>
</div>